# controllers:
#     resource:
#         path: ../src/Infrastructure/Controller/
#         namespace: App\Infrastructure\Controller
#     type: attribute
avail_endpoint:
    path: /api/avail
    methods: [GET]
    controller: App\Infrastructure\Controller\FlightController::getFlights
